begin;

alter table public.activities
    add column title_en text,
    add column description_en text,
    add column activity_type text not null default 'other',
    add column tags text[] not null default '{}';

alter table public.activities
    add constraint activities_title_en_length_check
        check (title_en is null or char_length(btrim(title_en)) between 1 and 120),
    add constraint activities_description_en_length_check
        check (description_en is null or char_length(description_en) <= 5000),
    add constraint activities_type_check
        check (activity_type in ('project', 'education', 'festival', 'exchange', 'competition', 'other')),
    add constraint activities_tags_count_check
        check (cardinality(tags) <= 12),
    add constraint activities_tags_length_check
        check (char_length(array_to_string(tags, '')) <= 360);

create index activities_type_date_idx
    on public.activities (activity_type, activity_date desc);

create index activities_tags_idx
    on public.activities using gin (tags);

update public.activities
set activity_type = case
    when title ilike '%체험전%' then 'education'
    when title ilike '%한어울제%' or title ilike '%축제%' then 'festival'
    when title ilike '%성과발표%' or title ilike '%대회%' then 'competition'
    when title ilike '%교류%' then 'exchange'
    when title ilike '%프로그래밍%' or title ilike '%Git%' then 'education'
    else activity_type
end;

create table public.content_revisions (
    id bigint generated by default as identity primary key,
    entity_type text not null,
    entity_id text not null,
    snapshot jsonb not null,
    changed_by uuid references auth.users (id) on delete set null,
    created_at timestamptz not null default now(),
    constraint content_revisions_entity_type_check
        check (entity_type in ('activity', 'site_content')),
    constraint content_revisions_entity_id_length_check
        check (char_length(entity_id) between 1 and 100),
    constraint content_revisions_snapshot_object_check
        check (jsonb_typeof(snapshot) = 'object')
);

comment on table public.content_revisions is
    'Administrator-only snapshots captured before activities or site content change.';

create index content_revisions_entity_created_idx
    on public.content_revisions (entity_type, entity_id, created_at desc);

create index content_revisions_created_at_idx
    on public.content_revisions (created_at desc);

alter table public.content_revisions enable row level security;

create policy content_revisions_select_admin
on public.content_revisions
for select
to authenticated
using (
    exists (
        select 1
        from public.site_admins
        where site_admins.user_id = (select auth.uid())
    )
);

revoke all on table public.content_revisions from public, anon, authenticated;
grant select on table public.content_revisions to authenticated;

create or replace function public.capture_activity_revision()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.content_revisions (
        entity_type,
        entity_id,
        snapshot,
        changed_by
    ) values (
        'activity',
        old.id::text,
        to_jsonb(old),
        (select auth.uid())
    );
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

create or replace function public.capture_site_content_revision()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.content_revisions (
        entity_type,
        entity_id,
        snapshot,
        changed_by
    ) values (
        'site_content',
        old.id,
        to_jsonb(old),
        (select auth.uid())
    );
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

revoke all on function public.capture_activity_revision() from public, anon, authenticated;
revoke all on function public.capture_site_content_revision() from public, anon, authenticated;

create trigger activities_capture_revision
before update or delete on public.activities
for each row execute function public.capture_activity_revision();

create trigger site_content_capture_revision
before update or delete on public.site_content
for each row execute function public.capture_site_content_revision();

update public.site_content
set content = jsonb_set(
    jsonb_set(
        content,
        '{faq}',
        '{"title":"자주 묻는 질문","subtitle":"ESC에 대해 자주 묻는 내용을 확인하세요.","items":[]}'::jsonb,
        true
    ),
    '{translations}',
    coalesce(content -> 'translations', '{}'::jsonb) || jsonb_build_object(
    'en', coalesce(content #> '{translations,en}', '{}'::jsonb) ||
    '{
      "meta": {
        "title": "ESC — Engineering Science of Computer",
        "description": "Official website of ESC, the computer engineering club at Hansung Science High School.",
        "keywords": "ESC, Hansung Science High School, computer engineering club"
      },
      "navigation": {
        "home": "Home",
        "about": "About",
        "activities": "Activities",
        "portfolio": "Portfolio",
        "faq": "FAQ",
        "contact": "Contact"
      },
      "about": {
        "title": "About ESC",
        "body_markdown": "Hello! We are ESC, the computer engineering club of Hansung Science High School.\n\nESC stands for **Engineering Science of Computer**.\n\nWe explore computer engineering through a variety of activities. Here are our plans for the {year} school year.",
        "plans_markdown": "- Learn programming languages and tools useful in everyday life and research.\n- Plan and operate educational activities for middle school students.\n- Build projects and run a booth for the school festival.\n- Exchange ideas with other computer science clubs."
      },
      "activity_plans": {
        "title": "Activity Plans",
        "subtitle": "ESC activities for the {year} school year.",
        "items": [
          {
            "title": "Math and Science Experience Fair",
            "description": "We plan and run hands-on learning activities for middle school students at the fair hosted by Hansung Science High School and Seodaemun-gu.",
            "icon": "bi-mortarboard-fill"
          },
          {
            "title": "Han-eoul School Festival",
            "description": "We build a project based on the year''s activities and operate an interactive festival booth.",
            "icon": "bi-shop-window"
          },
          {
            "title": "Seoul Student AI Development Showcase",
            "description": "We present projects developed by ESC at the Seoul Metropolitan Office of Education showcase.",
            "icon": "bi-robot"
          },
          {
            "title": "Exchange with Sejong Science High School",
            "description": "We exchange ideas and activities with CPU, Sejong Science High School''s computer science club.",
            "icon": "bi-people-fill"
          },
          {
            "title": "Programming Languages",
            "description": "We learn languages such as Python and C++ and apply them to AI, algorithms, and other projects.",
            "icon": "bi-code-slash"
          },
          {
            "title": "Git and Collaboration",
            "description": "We learn collaborative workflows with Git and GitHub and apply them to team projects.",
            "icon": "bi-git"
          }
        ]
      },
      "portfolio": {"title":"Activity Archive"},
      "contact": {
        "title": "Contact",
        "intro": "If you have any questions, please contact us using the information below."
      },
      "footer": {"admin_label":"Admin"},
      "faq": {
        "title":"Frequently Asked Questions",
        "subtitle":"Find answers to common questions about ESC.",
        "items":[]
      }
    }'::jsonb),
    true
)
where id = 'home';

commit;
